/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'muscle' : IDL.Null,
  'fatLoss' : IDL.Null,
  'running' : IDL.Null,
  'nutrition' : IDL.Null,
});
export const Article = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'category' : Category,
});
export const Goal = IDL.Record({
  'completedDays' : IDL.Nat,
  'name' : IDL.Text,
  'targetDistanceKm' : IDL.Float64,
  'targetDays' : IDL.Nat,
  'startDate' : IDL.Int,
});
export const RunLog = IDL.Record({
  'date' : IDL.Int,
  'distanceKm' : IDL.Float64,
  'notes' : IDL.Text,
  'caloriesBurned' : IDL.Nat,
});
export const PlanLevel = IDL.Variant({
  'intermediate' : IDL.Null,
  'beginner' : IDL.Null,
  'advanced' : IDL.Null,
});
export const PlanScheduleEntry = IDL.Record({
  'day' : IDL.Nat,
  'isRestDay' : IDL.Bool,
  'distanceKm' : IDL.Float64,
  'activity' : IDL.Text,
});
export const RunningPlan = IDL.Record({
  'level' : PlanLevel,
  'schedule' : IDL.Vec(PlanScheduleEntry),
});

export const idlService = IDL.Service({
  'addGoal' : IDL.Func([IDL.Text, IDL.Float64, IDL.Nat], [], []),
  'addRunLog' : IDL.Func([IDL.Float64, IDL.Nat, IDL.Text], [], []),
  'getArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
  'getArticlesByCategory' : IDL.Func([Category], [IDL.Vec(Article)], ['query']),
  'getGoals' : IDL.Func([], [IDL.Vec(Goal)], ['query']),
  'getRunLogs' : IDL.Func([], [IDL.Vec(RunLog)], ['query']),
  'getRunningPlanByLevel' : IDL.Func(
      [PlanLevel],
      [IDL.Opt(RunningPlan)],
      ['query'],
    ),
  'getRunningPlans' : IDL.Func([], [IDL.Vec(RunningPlan)], ['query']),
  'updateGoalProgress' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'muscle' : IDL.Null,
    'fatLoss' : IDL.Null,
    'running' : IDL.Null,
    'nutrition' : IDL.Null,
  });
  const Article = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'category' : Category,
  });
  const Goal = IDL.Record({
    'completedDays' : IDL.Nat,
    'name' : IDL.Text,
    'targetDistanceKm' : IDL.Float64,
    'targetDays' : IDL.Nat,
    'startDate' : IDL.Int,
  });
  const RunLog = IDL.Record({
    'date' : IDL.Int,
    'distanceKm' : IDL.Float64,
    'notes' : IDL.Text,
    'caloriesBurned' : IDL.Nat,
  });
  const PlanLevel = IDL.Variant({
    'intermediate' : IDL.Null,
    'beginner' : IDL.Null,
    'advanced' : IDL.Null,
  });
  const PlanScheduleEntry = IDL.Record({
    'day' : IDL.Nat,
    'isRestDay' : IDL.Bool,
    'distanceKm' : IDL.Float64,
    'activity' : IDL.Text,
  });
  const RunningPlan = IDL.Record({
    'level' : PlanLevel,
    'schedule' : IDL.Vec(PlanScheduleEntry),
  });
  
  return IDL.Service({
    'addGoal' : IDL.Func([IDL.Text, IDL.Float64, IDL.Nat], [], []),
    'addRunLog' : IDL.Func([IDL.Float64, IDL.Nat, IDL.Text], [], []),
    'getArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
    'getArticlesByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(Article)],
        ['query'],
      ),
    'getGoals' : IDL.Func([], [IDL.Vec(Goal)], ['query']),
    'getRunLogs' : IDL.Func([], [IDL.Vec(RunLog)], ['query']),
    'getRunningPlanByLevel' : IDL.Func(
        [PlanLevel],
        [IDL.Opt(RunningPlan)],
        ['query'],
      ),
    'getRunningPlans' : IDL.Func([], [IDL.Vec(RunningPlan)], ['query']),
    'updateGoalProgress' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };