/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Article {
  'title' : string,
  'content' : string,
  'tags' : Array<string>,
  'category' : Category,
}
export type Category = { 'muscle' : null } |
  { 'fatLoss' : null } |
  { 'running' : null } |
  { 'nutrition' : null };
export interface Goal {
  'completedDays' : bigint,
  'name' : string,
  'targetDistanceKm' : number,
  'targetDays' : bigint,
  'startDate' : bigint,
}
export type PlanLevel = { 'intermediate' : null } |
  { 'beginner' : null } |
  { 'advanced' : null };
export interface PlanScheduleEntry {
  'day' : bigint,
  'isRestDay' : boolean,
  'distanceKm' : number,
  'activity' : string,
}
export interface RunLog {
  'date' : bigint,
  'distanceKm' : number,
  'notes' : string,
  'caloriesBurned' : bigint,
}
export interface RunningPlan {
  'level' : PlanLevel,
  'schedule' : Array<PlanScheduleEntry>,
}
export interface _SERVICE {
  'addGoal' : ActorMethod<[string, number, bigint], undefined>,
  'addRunLog' : ActorMethod<[number, bigint, string], undefined>,
  'getArticles' : ActorMethod<[], Array<Article>>,
  'getArticlesByCategory' : ActorMethod<[Category], Array<Article>>,
  'getGoals' : ActorMethod<[], Array<Goal>>,
  'getRunLogs' : ActorMethod<[], Array<RunLog>>,
  'getRunningPlanByLevel' : ActorMethod<[PlanLevel], [] | [RunningPlan]>,
  'getRunningPlans' : ActorMethod<[], Array<RunningPlan>>,
  'updateGoalProgress' : ActorMethod<[bigint, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];