/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface PlanScheduleEntry {
    day: bigint;
    isRestDay: boolean;
    distanceKm: number;
    activity: string;
}
export interface RunningPlan {
    level: PlanLevel;
    schedule: Array<PlanScheduleEntry>;
}
export interface RunLog {
    date: bigint;
    distanceKm: number;
    notes: string;
    caloriesBurned: bigint;
}
export interface Article {
    title: string;
    content: string;
    tags: Array<string>;
    category: Category;
}
export interface Goal {
    completedDays: bigint;
    name: string;
    targetDistanceKm: number;
    targetDays: bigint;
    startDate: bigint;
}
export enum Category {
    muscle = "muscle",
    fatLoss = "fatLoss",
    running = "running",
    nutrition = "nutrition"
}
export enum PlanLevel {
    intermediate = "intermediate",
    beginner = "beginner",
    advanced = "advanced"
}
export interface backendInterface {
    addGoal(name: string, targetDistanceKm: number, targetDays: bigint): Promise<void>;
    addRunLog(distanceKm: number, caloriesBurned: bigint, notes: string): Promise<void>;
    getArticles(): Promise<Array<Article>>;
    getArticlesByCategory(category: Category): Promise<Array<Article>>;
    getGoals(): Promise<Array<Goal>>;
    getRunLogs(): Promise<Array<RunLog>>;
    getRunningPlanByLevel(level: PlanLevel): Promise<RunningPlan | null>;
    getRunningPlans(): Promise<Array<RunningPlan>>;
    updateGoalProgress(goalIndex: bigint, daysCompleted: bigint): Promise<void>;
}
import type { Article as _Article, Category as _Category, PlanLevel as _PlanLevel, PlanScheduleEntry as _PlanScheduleEntry, RunningPlan as _RunningPlan } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addGoal(arg0: string, arg1: number, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addGoal(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGoal(arg0, arg1, arg2);
            return result;
        }
    }
    async addRunLog(arg0: number, arg1: bigint, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addRunLog(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRunLog(arg0, arg1, arg2);
            return result;
        }
    }
    async getArticles(): Promise<Array<Article>> {
        if (this.processError) {
            try {
                const result = await this.actor.getArticles();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getArticles();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getArticlesByCategory(arg0: Category): Promise<Array<Article>> {
        if (this.processError) {
            try {
                const result = await this.actor.getArticlesByCategory(to_candid_Category_n6(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getArticlesByCategory(to_candid_Category_n6(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGoals(): Promise<Array<Goal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGoals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGoals();
            return result;
        }
    }
    async getRunLogs(): Promise<Array<RunLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRunLogs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRunLogs();
            return result;
        }
    }
    async getRunningPlanByLevel(arg0: PlanLevel): Promise<RunningPlan | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRunningPlanByLevel(to_candid_PlanLevel_n8(this._uploadFile, this._downloadFile, arg0));
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRunningPlanByLevel(to_candid_PlanLevel_n8(this._uploadFile, this._downloadFile, arg0));
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRunningPlans(): Promise<Array<RunningPlan>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRunningPlans();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRunningPlans();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateGoalProgress(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGoalProgress(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGoalProgress(arg0, arg1);
            return result;
        }
    }
}
function from_candid_Article_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Article): Article {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_Category_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_PlanLevel_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlanLevel): PlanLevel {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_RunningPlan_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RunningPlan): RunningPlan {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RunningPlan]): RunningPlan | null {
    return value.length === 0 ? null : from_candid_RunningPlan_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    level: _PlanLevel;
    schedule: Array<_PlanScheduleEntry>;
}): {
    level: PlanLevel;
    schedule: Array<PlanScheduleEntry>;
} {
    return {
        level: from_candid_PlanLevel_n13(_uploadFile, _downloadFile, value.level),
        schedule: value.schedule
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    content: string;
    tags: Array<string>;
    category: _Category;
}): {
    title: string;
    content: string;
    tags: Array<string>;
    category: Category;
} {
    return {
        title: value.title,
        content: value.content,
        tags: value.tags,
        category: from_candid_Category_n4(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    intermediate: null;
} | {
    beginner: null;
} | {
    advanced: null;
}): PlanLevel {
    return "intermediate" in value ? PlanLevel.intermediate : "beginner" in value ? PlanLevel.beginner : "advanced" in value ? PlanLevel.advanced : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    muscle: null;
} | {
    fatLoss: null;
} | {
    running: null;
} | {
    nutrition: null;
}): Category {
    return "muscle" in value ? Category.muscle : "fatLoss" in value ? Category.fatLoss : "running" in value ? Category.running : "nutrition" in value ? Category.nutrition : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Article>): Array<Article> {
    return value.map((x)=>from_candid_Article_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RunningPlan>): Array<RunningPlan> {
    return value.map((x)=>from_candid_RunningPlan_n11(_uploadFile, _downloadFile, x));
}
function to_candid_Category_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_PlanLevel_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlanLevel): _PlanLevel {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    muscle: null;
} | {
    fatLoss: null;
} | {
    running: null;
} | {
    nutrition: null;
} {
    return value == Category.muscle ? {
        muscle: null
    } : value == Category.fatLoss ? {
        fatLoss: null
    } : value == Category.running ? {
        running: null
    } : value == Category.nutrition ? {
        nutrition: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlanLevel): {
    intermediate: null;
} | {
    beginner: null;
} | {
    advanced: null;
} {
    return value == PlanLevel.intermediate ? {
        intermediate: null
    } : value == PlanLevel.beginner ? {
        beginner: null
    } : value == PlanLevel.advanced ? {
        advanced: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
